version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: busticket-mssql
    user: root
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Admin@123456"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
networks:
  busticket-network:
    driver: bridge