spring.application.name=BusTicket
spring.profiles.active=local

# SQL Server Configuration
# Lưu ý: trustServerCertificate=true cực kỳ quan trọng khi chạy Docker local
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=BusTicket;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=Admin@123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Đã sửa lỗi Dialect: Sử dụng class chung thay vì bản 2012 cũ
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.format_sql=true

# Server Configuration
server.port=8080

# Spring MVC Configuration
spring.mvc.converters.preferred-json-mapper=jackson